project:
  type: website

website:
  title: "Ishita Khanna"
  page-navigation: true
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: about.qmd
        text: About
      - href: resume.qmd
        text: Resume
      - href: mysticase.qmd
        text: Mysticase
    right:
      - icon: github
        href: https://github.com/ishitak22
      - icon: linkedin
        href: https://www.linkedin.com/in/khannaishita/
      

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme.scss, theme-dark.scss]
    respect-user-color-scheme: true
    include-in-header: animations.html
    toc: true

editor: visual

