---
title: "About me"
format: html
---

Hi, I'm **Ishita Khanna**, a data analyst with a focus on creating clear, insightful and impactful data-driven solutions.

I approach data projects with a blend of analytical thinking, attention to detail, and a user focused mindset, Whether it's exploring open datasets, designing dashboards, or building end-to-end workflows, I enjoy finding meaningful patterns and communicating results effectively.

My portfolio brings together applied projects across public health, retail, banking fraud, healthcare, ecommerce, and open-data storytelling. Through these projects, I focus on asking practical business questions, building visual explanations, and communicating insights in a way that is useful for decision-making.

I’m especially interested in roles where I can combine **data analysis, customer behaviour analysis, process improvement, dashboarding, and stakeholder communication** to create measurable business impact.

I'm always open to learning new techniques, tools and domains and excited to contribute wherever data can make a difference.

------------------------------------------------------------------------

## My Toolkit

-   **Data Analysis & Visualisation**: R, R Shiny, SQL, Tableau, Power BI, Python, Excel
-   **Machine Learning & GenAI**: Big data analysis, Generative AI, Predictive Modelling, Data Wrangling, Claude, Cursor
-   **Database**: MySQL, SQL Server, Supabase
-   **Programming & Automation**: HTML, CSS, KNIME, Zapier, Keap, Workflow Automation
-   **Cloud Computing & Version Control**: Databricks, Posit Cloud, Data Warehousing, Vercel, Git, GitHub
-   **Productivity & Collaboration**: Google Workspace, CRM Management, Process Documentation, Trello, Notion, Microsoft Office, Quarto
-   **Domain Knowledge & Professional Skills**: Business Analysis, Financial Modelling, Customer Data Analytics, Insights and Reporting, Segmentation Analysis, Supply Chain, Campaign Analysis, Statistical Analysis, Stakeholder Engagement, Data Storytelling, Cross-industry Adaptability

------------------------------------------------------------------------

## Get in Touch

-   [GitHub](https://github.com/ishitak22)
-   [LinkedIn](https://www.linkedin.com/in/khannaishita/)
-   Email: ishitakhanna2208\@gmail.com
